### ISSUE TITLE
dateLocal

### ISSUE THREAD

**Issue by masalmon** [masalmon/Ropenaq#12]
I'm not sure I'm parsing it right. Will make a commit today.

**Comment by jflasher** [comment]
Date parsing is probably my least favorite thing :sob:

**Comment by masalmon** [comment]
Is it date parsing OR knowing the difference between longitude and latitude? 😂

**Comment by jflasher** [comment]
Oh I have a lot of things I have issues with, don't get me started!

**Comment by masalmon** [comment]
The problem with dates is now solved.
