### ISSUE TITLE
aq_locations() fails

### ISSUE THREAD

**Issue by dirkschumacher** [masalmon/Ropenaq#15]
Hi,

first of all: great package!

This code fails with the following message:

```R
library(Ropenaq)
aq_locations(country='IN')
```
`> Error: data_frames can only contain 1d atomic vectors and lists`

Package version 0.1.

**Comment by masalmon** [comment]
Thanks for opening the issue! Working on it right now, I think I had missed an updated of jsonlite and I should soon solve the issue.

**Comment by masalmon** [comment]
Sooo now Travis build = success. I think I can close the issue now! If I'm lucky Appveyor will build as well.

Thanks again for installing the package and notifying the issue. I'm very sorry it had this bug! 

Last but not least, the package is not great, the API is!
