### ISSUE TITLE
Doesnt work with cities in Poland

### ISSUE THREAD

**Issue by masalmon** [masalmon/Ropenaq#4]

**Comment by jflasher** [comment]
Could be related to the way accent marks are being handled?

**Comment by masalmon** [comment]
Yes I am working on encoding... I saw an error when the function measurements checks whether the location is available, and moreover it made me realize than when constructing the query I do not change the encoding. And a query for "Marszalkowska" is not going to give any result, I need to translate it to "Marsza%C5%82kowska". Much fun ahead. :-)

**Comment by masalmon** [comment]
(having a stupid accent in my own first name, I cannot complain about accents in city names :-D)

**Comment by jflasher** [comment]
Haha. Yeah, it's a pain. I ran into a [similar issue](https://github.com/openaq/openaq-api/blob/ee2f1c56aa03ea3225521de99e2272bee38a796e/adapters/poland.js#L75-L108) a while back with the Polish data and did a manual fix until I realized there was a much easier way to do it. :(

**Comment by masalmon** [comment]
I'm happy I tried to download data for Warsaw, because I would not have seen this issue when using Indian data... Well I'll try to solve the issue in the next days. I guess I can translate the encoding to ASCII for the query. Thanks for commenting!

**Comment by jflasher** [comment]
No problem, thanks for catching it!

**Comment by masalmon** [comment]
I wanted to reproduce this graph https://pbs.twimg.com/media/CYOAGowW8AQs4Fy.png:large Turned out to be a good exercise!

**Comment by masalmon** [comment]
> Sys.setlocale("LC_CTYPE", "french") 
[1] "French_France.1252"
> URLencode("Marszałkowska")
[1] "Marszalkowska"
> 
> Sys.setlocale("LC_CTYPE", "russian") 
[1] "Russian_Russia.1251"
> URLencode("Marszałkowska")
[1] "Marszalkowska"
> 
> Sys.setlocale("LC_CTYPE", "polish") 
[1] "Polish_Poland.1250"
> URLencode("Marszałkowska")
[1] "Marsza%B3kowska"

**Comment by masalmon** [comment]
I'm starting to wonder whether I can really convert the string to the right encoding myself. I'd need to know in which language the name of the location was given. But can I really expect users to input location as "Marsza%B3kowska"? This seems quite complicated. 

@jflasher I guess the problem will be even more common as the platform grows (i.e. even more special characters)? If Polish is the only issue I could set the locale to Polish at the beginning of the function code and then back to the default setting at the end. :-)

Interestingly with setting the locale to Polish one can encode Vietnamese and Russian as well:
> Sys.setlocale("LC_CTYPE", "polish") 
[1] "Polish_Poland.1250"
> URLencode("ngắn")
[1] "ng%E1%BA%AFn"
> URLencode("наприме́р")
[1] "%D0%BD%D0%B0%D0%BF%D1%80%D0%B8%D0%BC%D0%B5%C2%B4%D1%80"

(well I do not know if this encoding makes sense) Whereas if the locale is anything but Polish the "ł" is recognized as a "l"... See https://bugs.r-project.org/bugzilla3/show_bug.cgi?id=16377 

 So maybe setting the locale to Polish is a good idea. I could add an argument language to all functions (cities, measurements, etc.) which by default would be Polish.

**Comment by jflasher** [comment]
I am pretty sure we already have some other sources with accent marks (I know Chile has some as well).  We are avoiding using 'local' names like наприме́р when they're provided in a romanicized form, but that doesn't really help too much here I don't think.

**Comment by masalmon** [comment]
Solution I'm going to implement: adding a URL encoded version of each column for cities, countries, locations, and expect URL encoded arguments in measurements and latest. Not fun for users but they could find the URL encoded version from cities, countries and locations functions. And thus I would not need any side effect of the function such as changing the locale. Now I'm gonna implement all this.

**Comment by jflasher** [comment]
Is there anything the API can do to make this easier?

**Comment by masalmon** [comment]
No thanks, I think it will work this way. Well only experience will tell us whether it really bother users but I think only URL encoded strings are universal and as long as I can translate them from cities() and locations() anyone can find the right URL encoded name to give to a city.

I just wonder how the Python package deals with it, but it may be a R-only problem.

**Comment by jflasher** [comment]
@dolugen @dhhagan have you run into anything along these lines in your projects?

**Comment by masalmon** [comment]
I think I have now solved the issue for the R package. I updated the README.

**Comment by dolugen** [comment]
I didn't run into a problem like this.

**Comment by dhhagan** [comment]
It is an 'issue' I guess with the python wrapper. Really it's just an encoding issue that the user can fix by encoding it the same way you have it stored in the database. I assume it's utf-8?

**Comment by jflasher** [comment]
@dhhagan yep, should be utf-8.

**Comment by dhhagan** [comment]
@jflasher The way I've always 'gotten around' any issues like this is to provide a `self_url` when returning the information..also helps quite a bit with cacheing. For example..when you make the `cities` api call..it would return all of the cities, with their urls as one of the meta fields..ie

    {
      'field1': answer1,
      'self-url': https://api.openaq.org/api/cities/[utf-8 encoded name here]/,
      ...
    }

That way, you can always just grab that from the response and use it. Is that something that you would be okay with adding? I can try to poke around later and send a PR. I'm in India now though..so internet is patchy at best.

**Comment by masalmon** [comment]
Regarding the R package, I now also expect the user to provide URL-encoded arguments. To help with this, for the functions that output cities/locations, I've added a column giving their URL-encoded versions. I could do a query for Warsaw without problem, which was a good test. However, I won't close this issue as long as the conversation is going on. ;-)
